//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaquetesTuristicos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class serviciosCREntities : DbContext
    {
        public serviciosCREntities()
            : base("name=serviciosCREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calificacion> Calificacions { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Orden> Ordens { get; set; }
        public virtual DbSet<Regular> Regulars { get; set; }
        public virtual DbSet<rolUsuario> rolUsuarios { get; set; }
        public virtual DbSet<ServiciosPorOrden> ServiciosPorOrdens { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
