//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaquetesTuristicos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regular
    {
        public int idUsuario { get; set; }
        public string primerNombre { get; set; }
        public string apellidos { get; set; }
        public decimal cuentaBancaria { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
